In [7]:
import numpy as np
import pandas as pd

In [8]:
df = pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [9]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

# Bag of words

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [11]:
#bag of words
bow = cv.fit_transform(df['text'])

In [19]:
#vocab
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [13]:
#convert into vector
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [15]:
#new sentence
cv.transform(['campusx watch and write comment of campusx']).toarray()
#OOV handeled

array([[2, 1, 0, 1, 1]])

# N-Grams

In [20]:
#we get one parameter for the countvectorized->n_grams=(1,1)->unigram, (2,2)->bigram
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2)) #bigram
#(1,2)->both unigram and bigram

In [21]:
#bag of words
bow = cv.fit_transform(df['text'])

In [22]:
#vocab
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [23]:
#convert into vector
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]


In [24]:
#new sentence
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[1, 0, 0, 0, 0, 1]])

# Tf-IDF

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [27]:
print(tfidf.idf_) #tfidf value is constant for each term only tf changes
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']
